author: 邹成卓 #  这里的值为发表文章的时候生成名称 主题作者：Barret Lee http://www.barretlee.com
author_en: zoucz

imgs:
  favicon: /favicon.ico
  avatar: /blogimgs/avatar.png
  avatar150: /blogimgs/avatar150.png
  app_icon: /blogimgs/app-icon.png
  bg: /blogimgs/bg.jpg
  loading: /blogimgs/loading.gif

pages:
  about: /about/
  friends: /friends/
  demos: /demos/
  feed: /atom.xml
  comments: /comments/
  message: /message/

# social
social:
  github: https://github.com/zouchengzhuo
  mail: 405966530@qq.com
  cnblog: http://tzyy.cnblogs.com

# Content
excerpt_link: 阅读全文 >>

duoshuo: zoucz
